import * as core from "@actions/core";
import * as fs from "fs";
import * as path from "path";

// ─────────────────────────────────────────────────────────────────────────────
// Changelog Writer — File I/O and merge logic
// ─────────────────────────────────────────────────────────────────────────────

const CHANGELOG_HEADER = `# Changelog

All notable changes to this project will be documented in this file.
This changelog is automatically generated by [MergeDoc](https://github.com/ArslanYM/mergedoc).

`;

/**
 * Reads the existing CHANGELOG.md (or creates a new one) and inserts
 * the new entry at the top, below the header.
 *
 * The insertion point is after the header block and any `## [Unreleased]`
 * section, so entries appear in reverse chronological order.
 */
export function updateChangelog(
  changelogPath: string,
  newEntry: string
): void {
  const absolutePath = path.resolve(process.cwd(), changelogPath);

  let existing = "";

  if (fs.existsSync(absolutePath)) {
    existing = fs.readFileSync(absolutePath, "utf-8");
    core.info(`📄 Found existing changelog at ${changelogPath}`);
  } else {
    core.info(`📄 No existing changelog found. Creating ${changelogPath}`);
  }

  const updated = mergeEntry(existing, newEntry);

  // Ensure the parent directory exists
  const dir = path.dirname(absolutePath);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }

  fs.writeFileSync(absolutePath, updated, "utf-8");
  core.info(`✅ Changelog updated: ${changelogPath}`);
}

/**
 * Merges a new entry into existing changelog content.
 *
 * If the file is empty/new, creates the full structure.
 * If it exists, finds the insertion point after the header and
 * any [Unreleased] section.
 */
function mergeEntry(existing: string, newEntry: string): string {
  if (!existing.trim()) {
    // Brand new changelog
    return CHANGELOG_HEADER + newEntry;
  }

  // Find insertion point: after the header block
  // The header ends at the first "## " heading (entry)
  const lines = existing.split("\n");
  let insertIndex = -1;

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i].trim();

    // Skip the main title and description
    if (line.startsWith("# ") && !line.startsWith("## ")) continue;

    // Skip [Unreleased] section
    if (line.startsWith("## [Unreleased]")) continue;

    // Found the first entry heading — insert before it
    if (line.startsWith("## ")) {
      insertIndex = i;
      break;
    }
  }

  if (insertIndex === -1) {
    // No existing entries — append after everything
    return existing.trimEnd() + "\n\n" + newEntry;
  }

  // Insert the new entry before the first existing entry
  const before = lines.slice(0, insertIndex).join("\n");
  const after = lines.slice(insertIndex).join("\n");

  return before.trimEnd() + "\n\n" + newEntry + after;
}
